- name: Install Nginx with content and with_fileglob on RedHat-like and Debian-like systems 
  hosts: all
  become: true
  
  vars:
    source_folder: "../website_content2"  # устанавливаем директорию, откуда будем копировать
    dest_folder_debian: "/var/www/html" # Путь назначения для дефолтной страницы на Debian-подобных системах
    dest_folder_redhat: "/usr/share/nginx/html" # Путь назначения для дефолтной страницы на RedHat-подобных системах

  tasks:
    - name: Ensure the Nginx package is installed 
      package: 
        name: nginx
        state: present
        update_cache: yes 

    - block: # Замена дефолтной страницы и запуск Nginx на Debian-подобных системах
      - name: 
        copy: 
          src: "{{ item }}"
          dest: "{{ dest_folder_debian }}"   
          mode: '0644' 
      with_fileglob: "{{ source_folder }}/*.*"   

      - name: Ensure nginx is running and enabled 
        service: name=nginx state=started enabled=yes
      when: ansible_os_family == "Debian"

    - block: # Замена дефолтной страницы и запуск Nginx на RedHat-подобных системах
      - name: Copy custom index.html to Nginx web root on RedHat-like systems
        copy: 
          src: "{{ source_folder }}/{{ item }}"  
          dest: "{{ dest_folder_redhat }}"   
          mode: '0644' 


      - name:  Reload or start nginx in container 
        shell: |
          nginx -t && nginx -s reload || nginx
        ignore_errors: true
      when: ansible_os_family == "RedHat"