---
- name: Install packages playbooks
  hosts: all
  become: yes

  tasks:
  # Обновляем кеш пакетов один раз, чтобы не выполнять при каждом шаге цикла
  - name: Update package cache on Debian-based systems
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Update package cache on RedHat-based systems
    yum:
      update_cache: yes
    when: ansible_os_family == "RedHat"

  # Выполняем установку пакетов в цикле
  - name: Install many packages
    package: name={{ item }} state=present update_cache=no
    loop: 
      - tree
      - tmux
      - tcpdump
      - dnsutils 
      - nmap
